### ISSUE TITLE
Change constant format

### ISSUE THREAD

**Issue by tarrencev** [statesauce/redux-saga-web3#16]
Right now we have `[method].call.CALL`, `[method].call.SUCCESS`, `[method].call.FAIL`

```
instance.attachMethod(
  "getEntry",
  types =>
    function*() {
      yield takeEvery(types.call.CALL, function*({
        meta,
        payload: { args, options },
      }) {
      }
})
```

Doing `call.CALL` seems silly. Maybe we should change to `call.INIT` and `send.INIT`

**Comment by sethfork** [comment]
Good idea - `types.call.CALL` is pretty awkward. I'll submit a PR for this change when I get a chance.
